# Generated by Django 4.2.6 on 2023-12-13 09:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("pcr", "0003_upload"),
    ]

    operations = [
        migrations.CreateModel(
            name="Amount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "amount",
                    models.IntegerField(
                        default=4,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="amounts",
                        to="pcr.analysis",
                    ),
                ),
                (
                    "kind",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="amounts",
                        to="pcr.kind",
                    ),
                ),
            ],
            options={
                "db_table": 'pcr"."amount',
                "ordering": ["kind", "analysis"],
            },
        ),
        migrations.AddConstraint(
            model_name="amount",
            constraint=models.UniqueConstraint(
                fields=("kind", "analysis"), name="unique_kind_analysis"
            ),
        ),
        migrations.AlterIndexTogether(
            name="amount",
            index_together={("kind", "analysis")},
        ),
    ]
