apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

images:
- name: kallepan/reagent-management-frontend
  newName: kallepan/reagent-management-frontend
  newTag: IMAGE_TAG