apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rms-db-pvc
  namespace: reagent-management
spec:
  storageClassName: longhorn
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi