version: "3.9"

services:
  app:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    command: sleep infinity
    depends_on:
      - db
    volumes:
      - ../../:/workspaces:cached
    networks:
      - default

  db:
    image: postgres:16.0-alpine
    env_file:
      - .env
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - default
    ports:
      - "5432:5432"

volumes:
  db-data:

networks:
  default:
    name: rms
