apiVersion: v1
kind: Service
metadata:
  name: rms-backend
  namespace: reagent-management
  labels:
    app: rms-django
    tier: backend
spec:
  selector:
    app: rms-django
    tier: backend
  ports:
    - protocol: TCP
      name: gunicorn
      port: 80
      targetPort: 9000