# Generated by Django 4.2.6 on 2023-10-27 14:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("bak", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("name", models.CharField(db_index=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": 'bak"."location',
            },
        ),
        migrations.CreateModel(
            name="Lot",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(db_index=True, max_length=50)),
                ("valid_from", models.DateField(blank=True, null=True)),
                ("valid_until", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(max_length=100)),
                ("in_use_from", models.DateField(blank=True, null=True)),
                ("in_use_until", models.DateField(blank=True, null=True)),
            ],
            options={
                "db_table": 'bak"."lot',
            },
        ),
        migrations.CreateModel(
            name="ReagentType",
            fields=[
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=50, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": 'bak"."reagent_type',
            },
        ),
        migrations.CreateModel(
            name="Reagent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.IntegerField(
                        db_index=True,
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(max_length=100)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="bak.location"
                    ),
                ),
                (
                    "lot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="bak.lot"
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bak.reagenttype",
                    ),
                ),
            ],
            options={
                "db_table": 'bak"."reagent',
            },
        ),
        migrations.AddConstraint(
            model_name="reagent",
            constraint=models.UniqueConstraint(
                fields=("type", "location", "lot"), name="unique_reagent"
            ),
        ),
    ]
