# Generated by Django 4.2.6 on 2023-11-09 09:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bak", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="type",
            name="article_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
