# Generated by Django 4.2.6 on 2023-11-23 13:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bak", "0005_add_locations"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="location",
            options={"ordering": ["name"]},
        ),
    ]
