# Generated by Django 4.2.6 on 2024-02-27 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bak", "0006_alter_location_options"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="lot",
            name="valid_from_before_valid_until",
        ),
        migrations.RemoveConstraint(
            model_name="lot",
            name="in_use_from_before_in_use_until",
        ),
        migrations.RemoveField(
            model_name="lot",
            name="in_use_from",
        ),
        migrations.RemoveField(
            model_name="lot",
            name="in_use_until",
        ),
    ]
